server:
  host: "localhoost"
  port: 8000
  max_header_bytes: 1048576
  read_timeout: 10s
  write_timeout: 10s

db:
  username: "postgres"
  password: "password"
  host: "localhost"
  port: 5432
  dbname: "newdb"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

token:
  access_keys:
    public_key_path: "./.env/access_token_key.pub"
    private_key_path: "./.env/access_token_key"
  refresh_keys:
    public_key_path: "./.env/refresh_token_key.pub"
    private_key_path: "./.env/refresh_token_key"
  access_expiration: 24h
  refresh_expiration: 720h
